optimize_config:
  # make villager no more spawn baby villager, but zombie.
  villager_spawn_zombie: false
  # how many zombies once the villager spawn when 'villager_spawn_zombie' is set to true.
  zombie_summon_count: 10
  # how many villager has AI in one chunk.
  villager_no_ai_limit: 3
  # stop all villager spawning.
  completely_no_new_villager: false
  # name the villager's name to one of the below names to avoid optimize.
  no_optimize_villager_name:
    - qwertyuiop
    - asdfghjkl
    - zxcvbnm